import{jsx as _jsx}from"react/jsx-runtime";import{forwardRef,useEffect}from"react";import{createStore}from"https://framer.com/m/framer/store.js@^1.0.0";import{randomColor}from"https://framer.com/m/framer/utils.js@^0.9.0";const useStore=createStore({background:"#0099FF"});export function withRotate(Component){return /*#__PURE__*/forwardRef((props,ref)=>{return /*#__PURE__*/_jsx(Component,{ref:ref,...props,animate:{rotate:90},transition:{duration:2}});});}export function withHover(Component){return /*#__PURE__*/forwardRef((props,ref)=>{return /*#__PURE__*/_jsx(Component,{ref:ref,...props,whileHover:{scale:1.05}});});}export function withRandomColor(Component){return /*#__PURE__*/forwardRef((props,ref)=>{const[store,setStore]=useStore();return /*#__PURE__*/_jsx(Component,{ref:ref,...props,animate:{background:store.background},onClick:()=>setStore({background:randomColor()})});});}// Typing dot animation — assign Dot0, Dot1, Dot2 to your three dots
const LOOP=1.2;const STAGGER=.18;const BOUNCE=6;function injectDotStyle(index){const id=`typing-dot-style-${index}`;if(document.getElementById(id))return;const delay=index*STAGGER;const s=(delay/LOOP*100).toFixed(1);const p=((delay+.2)/LOOP*100).toFixed(1);const l=((delay+.4)/LOOP*100).toFixed(1);const style=document.createElement("style");style.id=id;style.textContent=`
        @keyframes td${index} {
            0%,100% { transform: translateY(0); }
            ${s}%   { transform: translateY(0); }
            ${p}%   { transform: translateY(-${BOUNCE}px); }
            ${l}%   { transform: translateY(0); }
        }
        .typing-dot-${index} { animation: td${index} ${LOOP}s ease-in-out infinite; }
    `;document.head.appendChild(style);}function makeDot(index){return Component=>{return props=>{injectDotStyle(index);return /*#__PURE__*/_jsx("div",{className:`typing-dot-${index}`,style:{display:"contents"},children:/*#__PURE__*/_jsx(Component,{...props})});};};}export const Dot0=makeDot(0);export const Dot1=makeDot(1);export const Dot2=makeDot(2);export function Preserve3DDeep(Component){return props=>{return /*#__PURE__*/_jsx(Component,{...props,style:{...props.style,transformStyle:"preserve-3d",WebkitTransformStyle:"preserve-3d"}});};}// ─── Zoom-proof 100vh lock ───────────────────────────────────────────────────
// Captures window.innerHeight ONCE on mount and writes it as --vh to :root.
// Because we never re-run on resize/zoom, the section height stays locked
// to the original render size regardless of browser zoom level.
// Usage: assign withLockedVH to your sticky 100vh section in Framer.
function injectVHLock(){const id="vh-lock-style";if(document.getElementById(id))return;const style=document.createElement("style");style.id=id;style.textContent=`.vh-lock { height: calc(var(--vh, 1vh) * 100) !important; }`;document.head.appendChild(style);}function setVHOnce(){// Only set if not already set — preserves the first-render value across re-renders
if(document.documentElement.style.getPropertyValue("--vh"))return;const vh=window.innerHeight*.01;document.documentElement.style.setProperty("--vh",`${vh}px`);}export function withLockedVH(Component){return props=>{useEffect(()=>{injectVHLock();setVHOnce();},[])// empty dep array = runs once on mount, never again
;return /*#__PURE__*/_jsx(Component,{...props,style:{...props.style,height:"calc(var(--vh, 1vh) * 100)"}});};}
export const __FramerMetadata__ = {"exports":{"withRotate":{"type":"reactHoc","name":"withRotate","annotations":{"framerContractVersion":"1"}},"withLockedVH":{"type":"reactHoc","name":"withLockedVH","annotations":{"framerContractVersion":"1"}},"Dot2":{"type":"variable","annotations":{"framerContractVersion":"1"}},"Dot0":{"type":"variable","annotations":{"framerContractVersion":"1"}},"Preserve3DDeep":{"type":"reactHoc","name":"Preserve3DDeep","annotations":{"framerContractVersion":"1"}},"withRandomColor":{"type":"reactHoc","name":"withRandomColor","annotations":{"framerContractVersion":"1"}},"Dot1":{"type":"variable","annotations":{"framerContractVersion":"1"}},"withHover":{"type":"reactHoc","name":"withHover","annotations":{"framerContractVersion":"1"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./Examples.map